[Mon Mar 09 17:11:44.027308 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] mod_wsgi (pid=17536): Failed to exec Python script file 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi'.
[Mon Mar 09 17:11:44.027308 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] mod_wsgi (pid=17536): Exception occurred processing WSGI script 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi'.
[Mon Mar 09 17:11:44.041298 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] Traceback (most recent call last):\r
[Mon Mar 09 17:11:44.041298 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\numpy\\core\\__init__.py", line 24, in <module>\r
[Mon Mar 09 17:11:44.042299 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]     from . import multiarray\r
[Mon Mar 09 17:11:44.042299 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\numpy\\core\\multiarray.py", line 14, in <module>\r
[Mon Mar 09 17:11:44.042299 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]     from . import overrides\r
[Mon Mar 09 17:11:44.042299 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\numpy\\core\\overrides.py", line 7, in <module>\r
[Mon Mar 09 17:11:44.042299 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]     from numpy.core._multiarray_umath import (\r
[Mon Mar 09 17:11:44.042299 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] ImportError: DLL load failed while importing _multiarray_umath: Das angegebene Modul wurde nicht gefunden.\r
[Mon Mar 09 17:11:44.042299 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] \r
[Mon Mar 09 17:11:44.042299 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] During handling of the above exception, another exception occurred:\r
[Mon Mar 09 17:11:44.042299 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] \r
[Mon Mar 09 17:11:44.042299 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] Traceback (most recent call last):\r
[Mon Mar 09 17:11:44.043297 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi", line 5, in <module>\r
[Mon Mar 09 17:11:44.043297 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]     from app import app as application\r
[Mon Mar 09 17:11:44.043297 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website\\app.py", line 9, in <module>\r
[Mon Mar 09 17:11:44.043297 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]     import matplotlib.pyplot as plt\r
[Mon Mar 09 17:11:44.043297 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\matplotlib\\__init__.py", line 138, in <module>\r
[Mon Mar 09 17:11:44.043297 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]     from . import cbook, rcsetup\r
[Mon Mar 09 17:11:44.043297 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\matplotlib\\cbook\\__init__.py", line 31, in <module>\r
[Mon Mar 09 17:11:44.043297 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]     import numpy as np\r
[Mon Mar 09 17:11:44.043297 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\numpy\\__init__.py", line 142, in <module>\r
[Mon Mar 09 17:11:44.043297 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]     from . import core\r
[Mon Mar 09 17:11:44.043297 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\numpy\\core\\__init__.py", line 54, in <module>\r
[Mon Mar 09 17:11:44.043297 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]     raise ImportError(msg)\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] ImportError: \r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] \r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] \r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] Importing the numpy c-extensions failed.\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] - Try uninstalling and reinstalling numpy.\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] - If you have already done that, then:\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]   1. Check that you expected to use Python3.8 from "C:\\Apache24\\bin\\httpd.exe",\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]      and that you have no directories in your PATH or PYTHONPATH that can\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]      interfere with the Python and numpy version "1.18.1" you're trying to use.\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]   2. If (1) looks fine, you can open a new issue at\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]      https://github.com/numpy/numpy/issues.  Please include details on:\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]      - how you installed Python\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]      - how you installed numpy\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]      - your operating system\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]      - whether or not you have multiple versions of Python installed\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]      - if you built from source, your compiler versions and ideally a build log\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] \r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] - If you're working with a numpy git repository, try `git clean -xdf`\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524]   (removes all files not under version control) and rebuild numpy.\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] \r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] Note: this error has many possible causes, so please don't comment on\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] an existing issue about this - open a new one instead.\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] \r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] Original error was: DLL load failed while importing _multiarray_umath: Das angegebene Modul wurde nicht gefunden.\r
[Mon Mar 09 17:11:44.044302 2020] [wsgi:error] [pid 17536:tid 1336] [client ::1:51524] \r
[Mon Mar 09 17:18:50.663824 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] mod_wsgi (pid=7616): Failed to exec Python script file 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi'.
[Mon Mar 09 17:18:50.663824 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] mod_wsgi (pid=7616): Exception occurred processing WSGI script 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi'.
[Mon Mar 09 17:18:50.672814 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] Traceback (most recent call last):\r
[Mon Mar 09 17:18:50.672814 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\numpy\\core\\__init__.py", line 24, in <module>\r
[Mon Mar 09 17:18:50.672814 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]     from . import multiarray\r
[Mon Mar 09 17:18:50.672814 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\numpy\\core\\multiarray.py", line 14, in <module>\r
[Mon Mar 09 17:18:50.672814 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]     from . import overrides\r
[Mon Mar 09 17:18:50.672814 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\numpy\\core\\overrides.py", line 7, in <module>\r
[Mon Mar 09 17:18:50.672814 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]     from numpy.core._multiarray_umath import (\r
[Mon Mar 09 17:18:50.672814 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] ImportError: DLL load failed while importing _multiarray_umath: Das angegebene Modul wurde nicht gefunden.\r
[Mon Mar 09 17:18:50.672814 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] \r
[Mon Mar 09 17:18:50.672814 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] During handling of the above exception, another exception occurred:\r
[Mon Mar 09 17:18:50.672814 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] \r
[Mon Mar 09 17:18:50.672814 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] Traceback (most recent call last):\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi", line 5, in <module>\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]     from app import app as application\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website\\app.py", line 9, in <module>\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]     import matplotlib.pyplot as plt\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\matplotlib\\__init__.py", line 138, in <module>\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]     from . import cbook, rcsetup\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\matplotlib\\cbook\\__init__.py", line 31, in <module>\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]     import numpy as np\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\numpy\\__init__.py", line 142, in <module>\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]     from . import core\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\numpy\\core\\__init__.py", line 54, in <module>\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]     raise ImportError(msg)\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] ImportError: \r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] \r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] \r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] Importing the numpy c-extensions failed.\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] - Try uninstalling and reinstalling numpy.\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] - If you have already done that, then:\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]   1. Check that you expected to use Python3.8 from "C:\\Apache24\\bin\\httpd.exe",\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]      and that you have no directories in your PATH or PYTHONPATH that can\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]      interfere with the Python and numpy version "1.18.1" you're trying to use.\r
[Mon Mar 09 17:18:50.673812 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]   2. If (1) looks fine, you can open a new issue at\r
[Mon Mar 09 17:18:50.674813 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]      https://github.com/numpy/numpy/issues.  Please include details on:\r
[Mon Mar 09 17:18:50.674813 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]      - how you installed Python\r
[Mon Mar 09 17:18:50.674813 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]      - how you installed numpy\r
[Mon Mar 09 17:18:50.674813 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]      - your operating system\r
[Mon Mar 09 17:18:50.674813 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]      - whether or not you have multiple versions of Python installed\r
[Mon Mar 09 17:18:50.674813 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]      - if you built from source, your compiler versions and ideally a build log\r
[Mon Mar 09 17:18:50.674813 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] \r
[Mon Mar 09 17:18:50.674813 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] - If you're working with a numpy git repository, try `git clean -xdf`\r
[Mon Mar 09 17:18:50.674813 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567]   (removes all files not under version control) and rebuild numpy.\r
[Mon Mar 09 17:18:50.674813 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] \r
[Mon Mar 09 17:18:50.674813 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] Note: this error has many possible causes, so please don't comment on\r
[Mon Mar 09 17:18:50.674813 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] an existing issue about this - open a new one instead.\r
[Mon Mar 09 17:18:50.674813 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] \r
[Mon Mar 09 17:18:50.674813 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] Original error was: DLL load failed while importing _multiarray_umath: Das angegebene Modul wurde nicht gefunden.\r
[Mon Mar 09 17:18:50.674813 2020] [wsgi:error] [pid 7616:tid 1372] [client ::1:51567] \r
[Tue Mar 10 16:21:58.461350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639] [2020-03-10 16:21:58,443] ERROR in app: Exception on /webcam [GET]\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.461350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639] Traceback (most recent call last):\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.461350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 2446, in wsgi_app\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.461350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     response = self.full_dispatch_request()\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.461350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 1951, in full_dispatch_request\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.462350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     rv = self.handle_user_exception(e)\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.462350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 1820, in handle_user_exception\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.462350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     reraise(exc_type, exc_value, tb)\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.462350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\_compat.py", line 39, in reraise\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.462350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     raise value\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.462350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 1949, in full_dispatch_request\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.462350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     rv = self.dispatch_request()\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.462350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 1935, in dispatch_request\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.462350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     return self.view_functions[rule.endpoint](**req.view_args)\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.462350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website\\app_wsgi.py", line 61, in webcam\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.462350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     return render_template('webcam.html')\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.462350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\templating.py", line 137, in render_template\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.462350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     return _render(\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.462350 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\templating.py", line 120, in _render\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.463349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     rv = template.render(context)\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.463349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\jinja2\\asyncsupport.py", line 76, in render\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.463349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     return original_render(self, *args, **kwargs)\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.463349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\jinja2\\environment.py", line 1008, in render\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.463349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     return self.environment.handle_exception(exc_info, True)\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.463349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\jinja2\\environment.py", line 780, in handle_exception\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.463349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     reraise(exc_type, exc_value, tb)\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.463349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\jinja2\\_compat.py", line 37, in reraise\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.463349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     raise value.with_traceback(tb)\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.463349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "C:\\Users\\Oliver\\Desktop\\Masterarbeit\\03_Software\\Website\\templates\\webcam.html", line 2, in <module>\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.463349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     {% extends 'layout.html' %}\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.463349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\jinja2\\environment.py", line 1005, in render\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.463349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     return concat(self.root_render_func(self.new_context(vars)))\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.463349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "C:\\Users\\Oliver\\Desktop\\Masterarbeit\\03_Software\\Website\\templates\\webcam.html", line 16, in root\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.463349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     </video>\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.463349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "C:\\Users\\Oliver\\Desktop\\Masterarbeit\\03_Software\\Website\\templates\\layout.html", line 19, in root\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.464349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     padding-top: 100px;\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.464349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "C:\\Users\\Oliver\\Desktop\\Masterarbeit\\03_Software\\Website\\templates\\webcam.html", line 25, in block_body\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.464349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     // Variable, initialisiert zum html video element\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.464349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\jinja2\\runtime.py", line 262, in call\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.464349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     return __obj(*args, **kwargs)\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.464349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\helpers.py", line 370, in url_for\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.464349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     return appctx.app.handle_url_build_error(error, endpoint, values)\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.464349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 2215, in handle_url_build_error\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.464349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     reraise(exc_type, exc_value, tb)\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.464349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\_compat.py", line 39, in reraise\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.464349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     raise value\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.464349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\helpers.py", line 357, in url_for\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.464349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     rv = url_adapter.build(\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.464349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\werkzeug\\routing.py", line 2020, in build\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.464349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639]     raise BuildError(endpoint, values, method, self)\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:21:58.464349 2020] [wsgi:error] [pid 1676:tid 1344] [client ::1:61639] werkzeug.routing.BuildError: Could not build url for endpoint 'video_feed'. Did you mean 'index' instead?\r, referer: http://localhost/nutzung-pruefstand
[Tue Mar 10 16:31:02.230920 2020] [wsgi:error] [pid 12428:tid 1376] [client ::1:60054] mod_wsgi (pid=12428): Failed to exec Python script file 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi'.
[Tue Mar 10 16:31:02.230920 2020] [wsgi:error] [pid 12428:tid 1376] [client ::1:60054] mod_wsgi (pid=12428): Exception occurred processing WSGI script 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi'.
[Tue Mar 10 16:31:02.236921 2020] [wsgi:error] [pid 12428:tid 1376] [client ::1:60054] Traceback (most recent call last):\r
[Tue Mar 10 16:31:02.237920 2020] [wsgi:error] [pid 12428:tid 1376] [client ::1:60054]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi", line 5, in <module>\r
[Tue Mar 10 16:31:02.237920 2020] [wsgi:error] [pid 12428:tid 1376] [client ::1:60054]     from app_wsgi import app as application\r
[Tue Mar 10 16:31:02.237920 2020] [wsgi:error] [pid 12428:tid 1376] [client ::1:60054]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website\\app_wsgi.py", line 9, in <module>\r
[Tue Mar 10 16:31:02.237920 2020] [wsgi:error] [pid 12428:tid 1376] [client ::1:60054]     import matplotlib.pyplot as plt\r
[Tue Mar 10 16:31:02.237920 2020] [wsgi:error] [pid 12428:tid 1376] [client ::1:60054] ModuleNotFoundError: No module named 'matplotlib'\r
[Tue Mar 10 16:31:06.446443 2020] [wsgi:error] [pid 12428:tid 1332] [client ::1:60059] mod_wsgi (pid=12428): Failed to exec Python script file 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi'.
[Tue Mar 10 16:31:06.446443 2020] [wsgi:error] [pid 12428:tid 1332] [client ::1:60059] mod_wsgi (pid=12428): Exception occurred processing WSGI script 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi'.
[Tue Mar 10 16:31:06.447440 2020] [wsgi:error] [pid 12428:tid 1332] [client ::1:60059] Traceback (most recent call last):\r
[Tue Mar 10 16:31:06.447440 2020] [wsgi:error] [pid 12428:tid 1332] [client ::1:60059]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi", line 5, in <module>\r
[Tue Mar 10 16:31:06.447440 2020] [wsgi:error] [pid 12428:tid 1332] [client ::1:60059]     from app_wsgi import app as application\r
[Tue Mar 10 16:31:06.447440 2020] [wsgi:error] [pid 12428:tid 1332] [client ::1:60059]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website\\app_wsgi.py", line 9, in <module>\r
[Tue Mar 10 16:31:06.447440 2020] [wsgi:error] [pid 12428:tid 1332] [client ::1:60059]     import matplotlib.pyplot as plt\r
[Tue Mar 10 16:31:06.447440 2020] [wsgi:error] [pid 12428:tid 1332] [client ::1:60059] ModuleNotFoundError: No module named 'matplotlib'\r
[Tue Mar 10 17:28:46.765730 2020] [wsgi:error] [pid 22424:tid 1368] [client ::1:60702] mod_wsgi (pid=22424): Failed to exec Python script file 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi'.
[Tue Mar 10 17:28:46.765730 2020] [wsgi:error] [pid 22424:tid 1368] [client ::1:60702] mod_wsgi (pid=22424): Exception occurred processing WSGI script 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi'.
[Tue Mar 10 17:28:46.803707 2020] [wsgi:error] [pid 22424:tid 1368] [client ::1:60702] Traceback (most recent call last):\r
[Tue Mar 10 17:28:46.803707 2020] [wsgi:error] [pid 22424:tid 1368] [client ::1:60702]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi", line 5, in <module>\r
[Tue Mar 10 17:28:46.803707 2020] [wsgi:error] [pid 22424:tid 1368] [client ::1:60702]     from app_wsgi import app as application\r
[Tue Mar 10 17:28:46.803707 2020] [wsgi:error] [pid 22424:tid 1368] [client ::1:60702]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website\\app_wsgi.py", line 11\r
[Tue Mar 10 17:28:46.803707 2020] [wsgi:error] [pid 22424:tid 1368] [client ::1:60702]     from matplotlib\r
[Tue Mar 10 17:28:46.803707 2020] [wsgi:error] [pid 22424:tid 1368] [client ::1:60702]                   ^\r
[Tue Mar 10 17:28:46.803707 2020] [wsgi:error] [pid 22424:tid 1368] [client ::1:60702] SyntaxError: invalid syntax\r
[Tue Mar 10 17:45:46.337033 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857] [2020-03-10 17:45:46,322] ERROR in app: Exception on /webcam [GET]\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857] Traceback (most recent call last):\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 2446, in wsgi_app\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     response = self.full_dispatch_request()\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 1951, in full_dispatch_request\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     rv = self.handle_user_exception(e)\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 1820, in handle_user_exception\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     reraise(exc_type, exc_value, tb)\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\_compat.py", line 39, in reraise\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     raise value\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 1949, in full_dispatch_request\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     rv = self.dispatch_request()\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 1935, in dispatch_request\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     return self.view_functions[rule.endpoint](**req.view_args)\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website\\app.py", line 61, in webcam\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     return render_template('webcam.html')\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\templating.py", line 137, in render_template\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     return _render(\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\templating.py", line 120, in _render\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     rv = template.render(context)\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\jinja2\\asyncsupport.py", line 76, in render\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     return original_render(self, *args, **kwargs)\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\jinja2\\environment.py", line 1008, in render\r, referer: http://localhost/
[Tue Mar 10 17:45:46.338032 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     return self.environment.handle_exception(exc_info, True)\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\jinja2\\environment.py", line 780, in handle_exception\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     reraise(exc_type, exc_value, tb)\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\jinja2\\_compat.py", line 37, in reraise\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     raise value.with_traceback(tb)\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "C:\\Users\\Oliver\\Desktop\\Masterarbeit\\03_Software\\Website\\templates\\webcam.html", line 2, in <module>\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     {% extends 'layout.html' %}\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\jinja2\\environment.py", line 1005, in render\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     return concat(self.root_render_func(self.new_context(vars)))\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "C:\\Users\\Oliver\\Desktop\\Masterarbeit\\03_Software\\Website\\templates\\webcam.html", line 16, in root\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     </video>\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "C:\\Users\\Oliver\\Desktop\\Masterarbeit\\03_Software\\Website\\templates\\layout.html", line 19, in root\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     padding-top: 100px;\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "C:\\Users\\Oliver\\Desktop\\Masterarbeit\\03_Software\\Website\\templates\\webcam.html", line 25, in block_body\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     // Variable, initialisiert zum html video element\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\jinja2\\runtime.py", line 262, in call\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     return __obj(*args, **kwargs)\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\helpers.py", line 370, in url_for\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     return appctx.app.handle_url_build_error(error, endpoint, values)\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 2215, in handle_url_build_error\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     reraise(exc_type, exc_value, tb)\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\_compat.py", line 39, in reraise\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     raise value\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\helpers.py", line 357, in url_for\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     rv = url_adapter.build(\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\werkzeug\\routing.py", line 2020, in build\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857]     raise BuildError(endpoint, values, method, self)\r, referer: http://localhost/
[Tue Mar 10 17:45:46.339031 2020] [wsgi:error] [pid 15380:tid 1348] [client ::1:60857] werkzeug.routing.BuildError: Could not build url for endpoint 'video_feed'. Did you mean 'index' instead?\r, referer: http://localhost/

[Tue Mar 10 18:52:20.106418 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748] [2020-03-10 18:52:20,100] ERROR in app: Exception on /login [POST]\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.106418 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748] Traceback (most recent call last):\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 2446, in wsgi_app\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]     response = self.full_dispatch_request()\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 1951, in full_dispatch_request\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]     rv = self.handle_user_exception(e)\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 1820, in handle_user_exception\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]     reraise(exc_type, exc_value, tb)\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\_compat.py", line 39, in reraise\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]     raise value\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 1949, in full_dispatch_request\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]     rv = self.dispatch_request()\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\app.py", line 1935, in dispatch_request\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]     return self.view_functions[rule.endpoint](**req.view_args)\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website\\app.py", line 144, in login\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]     session['logged_in'] = True\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\werkzeug\\local.py", line 351, in __setitem__\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]     self._get_current_object()[key] = value\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]   File "c:\\users\\oliver\\anaconda3\\envs\\website\\lib\\site-packages\\flask\\sessions.py", line 102, in _fail\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748]     raise RuntimeError(\r, referer: http://localhost/login
[Tue Mar 10 18:52:20.107417 2020] [wsgi:error] [pid 1208:tid 1312] [client ::1:61748] RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.\r, referer: http://localhost/login
[Sat Mar 14 18:00:14.835172 2020] [wsgi:error] [pid 20484:tid 1336] [client ::1:57677] mod_wsgi (pid=20484): Failed to exec Python script file 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi'.
[Sat Mar 14 18:00:14.837172 2020] [wsgi:error] [pid 20484:tid 1336] [client ::1:57677] mod_wsgi (pid=20484): Exception occurred processing WSGI script 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi'.
[Sat Mar 14 18:00:14.887137 2020] [wsgi:error] [pid 20484:tid 1336] [client ::1:57677] Traceback (most recent call last):\r
[Sat Mar 14 18:00:14.887137 2020] [wsgi:error] [pid 20484:tid 1336] [client ::1:57677]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi", line 5, in <module>\r
[Sat Mar 14 18:00:14.888138 2020] [wsgi:error] [pid 20484:tid 1336] [client ::1:57677]     from app import app as application\r
[Sat Mar 14 18:00:14.888138 2020] [wsgi:error] [pid 20484:tid 1336] [client ::1:57677] ModuleNotFoundError: No module named 'app'\r
[Sat Mar 14 18:03:50.928687 2020] [wsgi:error] [pid 9088:tid 1336] [client ::1:57741] mod_wsgi (pid=9088): Failed to exec Python script file 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi'.
[Sat Mar 14 18:03:50.928687 2020] [wsgi:error] [pid 9088:tid 1336] [client ::1:57741] mod_wsgi (pid=9088): Exception occurred processing WSGI script 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi'.
[Sat Mar 14 18:03:50.932689 2020] [wsgi:error] [pid 9088:tid 1336] [client ::1:57741] Traceback (most recent call last):\r
[Sat Mar 14 18:03:50.932689 2020] [wsgi:error] [pid 9088:tid 1336] [client ::1:57741]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/web.wsgi", line 5, in <module>\r
[Sat Mar 14 18:03:50.932689 2020] [wsgi:error] [pid 9088:tid 1336] [client ::1:57741]     from project.app import app as application\r
[Sat Mar 14 18:03:50.932689 2020] [wsgi:error] [pid 9088:tid 1336] [client ::1:57741]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website\\project\\app.py", line 11, in <module>\r
[Sat Mar 14 18:03:50.932689 2020] [wsgi:error] [pid 9088:tid 1336] [client ::1:57741]     import app_helpers\r
[Sat Mar 14 18:03:50.932689 2020] [wsgi:error] [pid 9088:tid 1336] [client ::1:57741] ModuleNotFoundError: No module named 'app_helpers'\r
[Sat Mar 14 18:49:05.039690 2020] [wsgi:error] [pid 21056:tid 1328] [client ::1:55800] mod_wsgi (pid=21056): Failed to exec Python script file 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi'.
[Sat Mar 14 18:49:05.040690 2020] [wsgi:error] [pid 21056:tid 1328] [client ::1:55800] mod_wsgi (pid=21056): Exception occurred processing WSGI script 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi'.
[Sat Mar 14 18:49:05.063679 2020] [wsgi:error] [pid 21056:tid 1328] [client ::1:55800] Traceback (most recent call last):\r
[Sat Mar 14 18:49:05.063679 2020] [wsgi:error] [pid 21056:tid 1328] [client ::1:55800]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi", line 5, in <module>\r
[Sat Mar 14 18:49:05.063679 2020] [wsgi:error] [pid 21056:tid 1328] [client ::1:55800]     from app import app as application\r
[Sat Mar 14 18:49:05.063679 2020] [wsgi:error] [pid 21056:tid 1328] [client ::1:55800] ModuleNotFoundError: No module named 'app'\r
[Sat Mar 14 18:51:03.170574 2020] [wsgi:error] [pid 10144:tid 1328] [client ::1:55816] mod_wsgi (pid=10144): Failed to exec Python script file 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi'.
[Sat Mar 14 18:51:03.171576 2020] [wsgi:error] [pid 10144:tid 1328] [client ::1:55816] mod_wsgi (pid=10144): Exception occurred processing WSGI script 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi'.
[Sat Mar 14 18:51:03.198558 2020] [wsgi:error] [pid 10144:tid 1328] [client ::1:55816] Traceback (most recent call last):\r
[Sat Mar 14 18:51:03.198558 2020] [wsgi:error] [pid 10144:tid 1328] [client ::1:55816]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi", line 5, in <module>\r
[Sat Mar 14 18:51:03.198558 2020] [wsgi:error] [pid 10144:tid 1328] [client ::1:55816]     from app import app as application\r
[Sat Mar 14 18:51:03.198558 2020] [wsgi:error] [pid 10144:tid 1328] [client ::1:55816] ModuleNotFoundError: No module named 'app'\r
[Sat Mar 14 18:51:07.891077 2020] [wsgi:error] [pid 10144:tid 1328] [client ::1:55820] mod_wsgi (pid=10144): Failed to exec Python script file 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi'.
[Sat Mar 14 18:51:07.891077 2020] [wsgi:error] [pid 10144:tid 1328] [client ::1:55820] mod_wsgi (pid=10144): Exception occurred processing WSGI script 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi'.
[Sat Mar 14 18:51:07.891077 2020] [wsgi:error] [pid 10144:tid 1328] [client ::1:55820] Traceback (most recent call last):\r
[Sat Mar 14 18:51:07.892077 2020] [wsgi:error] [pid 10144:tid 1328] [client ::1:55820]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi", line 5, in <module>\r
[Sat Mar 14 18:51:07.892077 2020] [wsgi:error] [pid 10144:tid 1328] [client ::1:55820]     from app import app as application\r
[Sat Mar 14 18:51:07.892077 2020] [wsgi:error] [pid 10144:tid 1328] [client ::1:55820] ModuleNotFoundError: No module named 'app'\r
[Fri Mar 20 15:12:15.768421 2020] [wsgi:error] [pid 20464:tid 1336] [client ::1:54173] mod_wsgi (pid=20464): Failed to exec Python script file 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi'.
[Fri Mar 20 15:12:15.769418 2020] [wsgi:error] [pid 20464:tid 1336] [client ::1:54173] mod_wsgi (pid=20464): Exception occurred processing WSGI script 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi'.
[Fri Mar 20 15:12:15.773414 2020] [wsgi:error] [pid 20464:tid 1336] [client ::1:54173] Traceback (most recent call last):\r
[Fri Mar 20 15:12:15.773414 2020] [wsgi:error] [pid 20464:tid 1336] [client ::1:54173]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi", line 5, in <module>\r
[Fri Mar 20 15:12:15.773414 2020] [wsgi:error] [pid 20464:tid 1336] [client ::1:54173]     from app import app as application\r
[Fri Mar 20 15:12:15.773414 2020] [wsgi:error] [pid 20464:tid 1336] [client ::1:54173]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project\\app.py", line 10, in <module>\r
[Fri Mar 20 15:12:15.773414 2020] [wsgi:error] [pid 20464:tid 1336] [client ::1:54173]     from Website.project import app_helpers  # own modules\r
[Fri Mar 20 15:12:15.774415 2020] [wsgi:error] [pid 20464:tid 1336] [client ::1:54173] ModuleNotFoundError: No module named 'Website'\r
[Fri Mar 20 15:12:24.967199 2020] [wsgi:error] [pid 20464:tid 1336] [client ::1:54191] mod_wsgi (pid=20464): Failed to exec Python script file 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi'.
[Fri Mar 20 15:12:24.967199 2020] [wsgi:error] [pid 20464:tid 1336] [client ::1:54191] mod_wsgi (pid=20464): Exception occurred processing WSGI script 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi'.
[Fri Mar 20 15:12:24.968200 2020] [wsgi:error] [pid 20464:tid 1336] [client ::1:54191] Traceback (most recent call last):\r
[Fri Mar 20 15:12:24.968200 2020] [wsgi:error] [pid 20464:tid 1336] [client ::1:54191]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi", line 5, in <module>\r
[Fri Mar 20 15:12:24.968200 2020] [wsgi:error] [pid 20464:tid 1336] [client ::1:54191]     from app import app as application\r
[Fri Mar 20 15:12:24.968200 2020] [wsgi:error] [pid 20464:tid 1336] [client ::1:54191]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project\\app.py", line 10, in <module>\r
[Fri Mar 20 15:12:24.968200 2020] [wsgi:error] [pid 20464:tid 1336] [client ::1:54191]     from Website.project import app_helpers  # own modules\r
[Fri Mar 20 15:12:24.968200 2020] [wsgi:error] [pid 20464:tid 1336] [client ::1:54191] ModuleNotFoundError: No module named 'Website'\r
[Fri Mar 20 15:16:03.679425 2020] [wsgi:error] [pid 6924:tid 1328] [client ::1:54394] mod_wsgi (pid=6924): Failed to exec Python script file 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi'.
[Fri Mar 20 15:16:03.679425 2020] [wsgi:error] [pid 6924:tid 1328] [client ::1:54394] mod_wsgi (pid=6924): Exception occurred processing WSGI script 'C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi'.
[Fri Mar 20 15:16:03.685423 2020] [wsgi:error] [pid 6924:tid 1328] [client ::1:54394] Traceback (most recent call last):\r
[Fri Mar 20 15:16:03.685423 2020] [wsgi:error] [pid 6924:tid 1328] [client ::1:54394]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project/web.wsgi", line 5, in <module>\r
[Fri Mar 20 15:16:03.685423 2020] [wsgi:error] [pid 6924:tid 1328] [client ::1:54394]     from app import app as application\r
[Fri Mar 20 15:16:03.685423 2020] [wsgi:error] [pid 6924:tid 1328] [client ::1:54394]   File "C:/Users/Oliver/Desktop/Masterarbeit/03_Software/Website/project\\app.py", line 10, in <module>\r
[Fri Mar 20 15:16:03.685423 2020] [wsgi:error] [pid 6924:tid 1328] [client ::1:54394]     from Website.project import app_helpers  # own modules\r
[Fri Mar 20 15:16:03.685423 2020] [wsgi:error] [pid 6924:tid 1328] [client ::1:54394] ModuleNotFoundError: No module named 'Website'\r
[Fri Mar 20 15:18:38.479748 2020] [wsgi:error] [pid 11764:tid 1324] [client ::1:54558] Test gestartet, ID: 11\r, referer: http://localhost/dashboard
[Fri Mar 20 15:18:48.147471 2020] [wsgi:error] [pid 11764:tid 1324] [client ::1:54570] Test gestartet, ID: 11\r, referer: http://localhost/dashboard
[Fri Mar 20 15:18:58.776949 2020] [wsgi:error] [pid 11764:tid 1324] [client ::1:59014] Test gestartet, ID: 13\r, referer: http://localhost/dashboard
[Fri Mar 20 15:24:38.177351 2020] [wsgi:error] [pid 11764:tid 1324] [client ::1:59348] Test gestartet, ID: 11\r, referer: http://localhost/dashboard
[Fri Mar 20 15:27:32.469570 2020] [wsgi:error] [pid 15288:tid 1368] [client ::1:59520] Test gestartet, ID: 11\r, referer: http://localhost/dashboard
[Fri Mar 20 15:43:47.789491 2020] [wsgi:error] [pid 19960:tid 1336] [client ::1:60455] Test gestartet, ID: 11\r, referer: http://localhost/dashboard
[Fri Mar 20 15:44:00.040631 2020] [wsgi:error] [pid 19960:tid 1336] [client ::1:60474] Test gestartet, ID: 13\r, referer: http://localhost/dashboard
[Fri Mar 20 22:34:12.596606 2020] [wsgi:error] [pid 22388:tid 1328] [client ::1:56091] Test mit folgender ID wird gestartet, ID: 11\r, referer: http://localhost/dashboard
[Sat Mar 21 15:09:02.592578 2020] [wsgi:error] [pid 19260:tid 1340] [client ::1:60823] result.id = 18\r, referer: http://localhost/dashboard
